### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by sunl888** [leon-fong/ChatGPT-miniprogram#3]
请问我可以部署到自己的微信小程序中吗？（自己学习使用）

**Comment by leon-fong** [comment]
本项目使用 [MIT](https://github.com/leon-fong/chatgpt-miniprogram/blob/2ff122dfe357659134cd7589a2e4520c48fbee18/LICENSE) 协议 ，请自由地享受和参与开源。

**Comment by erbanku** [comment]
> 本项目使用 [MIT](https://github.com/leon-fong/chatgpt-miniprogram/blob/2ff122dfe357659134cd7589a2e4520c48fbee18/LICENSE) 协议 ，请自由地享受和参与开源。

好家伙，刚下完代码和微信开发者工具，顺便想试一下Demo,发现被腾讯停止访问了，算了还是不跟腾讯玩了，做一个网页或者app用吧，不过感谢。
