### ISSUE TITLE
baseUrl配置了这个：https://bypass.churchless.tech/api/conversation

### ISSUE THREAD

**Issue by 90tech** [leon-fong/ChatGPT-miniprogram#4]
baseUrl配置了这个：https://bypass.churchless.tech/api/conversation ，一直报服务请求错误，设置成官方https://api.openai.com/v1/chat/completions的也报这个？

**Comment by 90tech** [comment]
发现用官方的api。调试模式可以接受消息，预览直接报服务请求错误嘞？

**Comment by leon-fong** [comment]
> 发现用官方的api。调试模式可以接受消息，预览直接报服务请求错误嘞？

需要在微信公众平台后台配置合法域名，预览时需要在手机端打开【开发调试】
